stages:
  - build
  - setup
  - test                # unit tests validation
  - ctf-super-easy      # "Super easy" CTF challenges coming out of PentestPerf
  - ctf-easy            # "Easy" CTF challenges coming out of PentestPerf
  - ctf-medium          # "Medium" CTF challenges coming out of PentestPerf
  - ctf-hard            # "Hard" CTF challenges coming out of PentestPerf
  - ctf-super-hard      # "Super hard" CTF challenges coming out of PentestPerf

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone
  GIT_DEPTH: "20"
  VERSION: "0.1"
  DISTRO: ubuntu:22.04

services:
  - name: docker:dind
    command: ["--tls=true", "--tlsverify=false"]
    entrypoint: ["sh", "-c", "dockerd-entrypoint.sh && sleep 5"]

include:
  - project: 'aliasrobotics/alias_research/cai'
    ref: main
    file:
      - 'ci/build/.build.yml'
      - 'ci/test/.test.yml'

before_script:
  - |
    for i in $(seq 1 30); do
      docker info && break
      echo "Waiting for Docker to start..."
      sleep 1
    done
    docker info
