stages:
  - build
  - setup
  - test                # unit tests validation
  - ctf-super-easy      # "Super easy" CTF challenges coming out of PentestPerf
  - ctf-easy            # "Easy" CTF challenges coming out of PentestPerf
  - ctf-medium          # "Medium" CTF challenges coming out of PentestPerf
  - ctf-hard            # "Hard" CTF challenges coming out of PentestPerf
  - ctf-super-hard      # "Super hard" CTF challenges coming out of PentestPerf

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  VERSION: "0.1"
  DISTRO: ubuntu:22.04
  CI_DEBUG_TRACE: "true"
  GIT_FETCH_TIMEOUT: 300

services:
  - name: docker:dind
    alias: docker

include:
  - project: 'aliasrobotics/alias_research/cai'
    ref: main
    file:
      - 'ci/build/.build.yml'                # build
      #- 'ci/setup/.setup.yml'               # setup
      - 'ci/test/.test.yml'                  # test
      #- 'ci/ctfs/.ctf.yml'                  # ctf
