
.use_base_container: &use_base_container
  stage: test
  image: "${CI_REGISTRY_IMAGE}:latest"
services:
  - name: docker:dind
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock", "--dns=8.8.8.8", "--dns=8.8.4.4"]

.run_ctf: &run_ctf
  <<: *use_base_container
  before_script:
    - |
      for i in $(seq 1 5); do
        echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY_IMAGE && break || sleep 10

        echo "Retrying docker login ($i/5)..."
      done
  script:
    - unset DOCKER_HOST
    - pip3 uninstall pentestperf --yes  # remove old version
    - pip3 install -e .
    - msfrpcd -P cai > /dev/null 2>&1 &
    - |
      # Set additional environment variables if defined
      for var in $(compgen -e); do
        if [[ $var == CTF_* && -n ${!var} ]]; then
          export $var="${!var}"
        fi
      done
    - pytest -s tests/ctfs/test_generic.py  # NOTE: hardcoded file name
  artifacts:
    paths:
      - cai.png
      - cai.dot
      - logs
    expire_in: 1 month  # Retain the artifacts for 1 month
  tags:
    - p40
    - x86
  rules:
    - if: $CI_COMMIT_BRANCH
      when: on_success

################################################################################
# CTF
################################################################################

🚩 picoctf_static_flag | qw:14b:
   <<: *run_ctf
   stage: ctf-super-easy
   variables:
     CTF_NAME: picoctf_static_flag
     CTF_MODEL: qwen2.5:14b
     CTF_RERUN: 5

# 🚩 chal1 | qw:14b:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: chal1
#      CTF_MODEL: qwen2.5:14b
#      CTF_RERUN: 5

# 🚩 kiddoctf | qw:14b | i:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: kiddoctf
#      CTF_MODEL: qwen2.5:14b
#      CTF_CHALLENGE: '01 linux i'
#      CTF_RERUN: 5

# 🚩 kiddoctf | qw:14b | ii:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: kiddoctf
#      CTF_MODEL: qwen2.5:14b
#      CTF_CHALLENGE: '02 linux ii'
#      CTF_RERUN: 5

# 🚩 kiddoctf | qw:14b | iii:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: kiddoctf
#      CTF_MODEL: qwen2.5:14b
#      CTF_CHALLENGE: '03 linux iii'
#      CTF_RERUN: 5

# 🚩 kiddoctf | qw:14b | iv:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: kiddoctf
#      CTF_MODEL: qwen2.5:14b
#      CTF_CHALLENGE: '04 linux iv'
#      CTF_RERUN: 5

# 🚩 my_first_pwnie | qw:14b:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: my_first_pwnie
#      CTF_MODEL: qwen2.5:14b
#      CTF_RERUN: 5

# 🚩 picoctf_reversing_python | qw:14b:
#    <<: *run_ctf
#    stage: ctf-super-easy
#    variables:
#      CTF_NAME: picoctf_reversing_python
#      CTF_MODEL: qwen2.5:14b
#      CTF_RERUN: 5
